version: "3.8"
services:
  app:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 1337:1337
    volumes:
      - "./frontend:/app"
    networks:
      - private
  mongo:
    image: mongo:5.0.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
    networks:
      - private

  api:
    restart: always
    build:
        context: ./api
        dockerfile: Dockerfile
    ports:
        - 8441:8441

  embeddings:
    restart: always
    build:
      context: ./hf-text-embeddings-inference
      dockerfile: Dockerfile
    ports:
      - 8442:80

networks:
  private: