version: '3.7'
services:

########################################
##### SQL Server - MySQLDB         #####
########################################

  app_sqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'development_instance_root_password'
      MYSQL_DATABASE: 'app_database'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'development_instance_password'
      TZ: 'Asia/Kolkata'
    volumes:
      - app_mysql_volume:/var/lib/mysql
    networks:
      - private


########################################
##### PHP-FPM Application Server   #####
########################################

  app_application:
    build:
      context: .
      dockerfile: ./config/FPM.Dockerfile
    restart: always
    links:
      - app_sqldb
    environment:
      TZ: 'Asia/Kolkata'
    volumes:
      - ./prompt_receiver:/app
    networks:
      - private

########################################
##### NginX Web Server             #####
########################################

  app_webserver:
    image: nginx:latest
    restart: always
    links:
      - app_application
    environment:
      TZ: 'Asia/Kolkata'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./prompt_receiver:/app
    ports: 
      - 8443:80
    networks:
      - public
      - private

volumes:
  app_mysql_volume:

networks:
  public:
    external: true
  private:
    driver: bridge
